### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by davidbdyer** [klemens/rconc#2]
I guess this means it wont run on Mac OS?

error[E0282]: type annotations needed
  --> /Users/david/.cargo/registry/src/github.com-1ecc6299db9ec823/app_dirs-1.1.1/src/imp/platform/macos.rs:10:31
   |
10 |         Ok(Component::RootDir.as_ref().into())
   |            -------------------^^^^^^--
   |            |                  |
   |            |                  cannot infer type for type parameter `T`
   |            this method call resolves to `&T`
   |
   = note: type must be known at this point

**Comment by klemens** [comment]
No it should work on all platforms. I guess I just have to update my dependencies, I last compiled this more then 3 years ago. :wink:

**Comment by klemens** [comment]
This is now fixed with v0.1.2. Note that I currently don't have a minecraft (or any other RCON) server running, so I could only do some basic sanity tests. Hope I didn't break anything. :sweat_smile:

**Comment by davidbdyer** [comment]
Thanks, i appreciate the fix. I don't quiet know enough to do it myself yet.
